// courseIcons.js
import {
  FaUser,
  FaBook,
  FaLaptop,
  FaChalkboardTeacher,
  FaCode,
  FaDatabase,
  FaPaintBrush,
  FaCamera,
  FaMusic,
  FaVideo,
  FaGlobe,
  FaCloud,
  FaMobileAlt,
  FaNetworkWired,
  FaServer,
  FaRobot,
  FaBrain,
  FaLanguage,
  FaGraduationCap,
  FaFlask,
  FaLeaf,
  FaShoppingCart,
  FaChartLine,
  FaMoneyBillWave,
  FaRegLightbulb,
  FaCogs,
  FaBolt,
  FaLock,
  FaKeyboard,
  FaPuzzlePiece,
  FaWrench,
  FaCompass,
  FaRunning,
  FaDumbbell,
  FaHeartbeat,
  FaHospital,
  FaPills,
  FaMedkit,
  FaStethoscope,
  FaAppleAlt,
  FaCar,
  FaBus,
  FaPlane,
  FaShip,
  FaBicycle,
  FaTractor,
  FaGamepad,
  FaRocket,
  FaAtom,
  FaMicroscope,
  FaBookOpen,
  FaPenFancy,
  FaTheaterMasks,
  FaFilm,
  FaPodcast,
  FaBell,
  FaEnvelope,
  FaPhone,
  FaClock,
  FaCalendarAlt,
  FaMapMarkedAlt,
  FaBuilding,
  FaUniversity,
  FaIndustry,
  FaTools,
  FaHammer,
  FaBrush,
  FaPencilAlt,
  FaLightbulb,
  FaSun,
  FaMoon,
  FaStar,
  FaHeart,
  FaSmile,
  FaFrown,
  FaDog,
  FaCat,
  FaFish,
  FaHorse,
  FaTree,
  FaMountain,
  FaWater,
  FaFire,
  FaRecycle,
  FaGift,
  FaShoppingBag,
  FaCreditCard,
  FaWallet,
  FaLaptopCode,
  FaMicrochip,
  FaSatellite,
  FaSpaceShuttle,
  FaTrophy,
  FaMedal,
  FaFlag,
  FaGlasses,
  FaPenNib,
  FaBox,
  FaArchive,
} from "react-icons/fa";
import {
  FaReact,
  FaNodeJs,
  FaPython,
  FaJava,
  FaPhp,
  FaHtml5,
  FaCss3,
  FaAngular,
  FaVuejs,
  FaGitAlt,
  FaDocker,
  FaAws,
} from "react-icons/fa";
import {
  SiNextdotjs,
  SiMongodb,
  SiTailwindcss,
  SiTypescript,
  SiKubernetes,
  SiGraphql,
  SiDjango,
  SiSpring,
  SiPostgresql,
  SiMysql,
} from "react-icons/si";
import { DiJavascript1 } from "react-icons/di";

export const courseIcons = [
  { label: "User", value: "FaUser", icon: FaUser },
  { label: "Book", value: "FaBook", icon: FaBook },
  { label: "Laptop", value: "FaLaptop", icon: FaLaptop },
  { label: "Teacher", value: "FaChalkboardTeacher", icon: FaChalkboardTeacher },
  { label: "Code", value: "FaCode", icon: FaCode },
  { label: "Database", value: "FaDatabase", icon: FaDatabase },
  { label: "Art", value: "FaPaintBrush", icon: FaPaintBrush },
  { label: "Camera", value: "FaCamera", icon: FaCamera },
  { label: "Music", value: "FaMusic", icon: FaMusic },
  { label: "Video", value: "FaVideo", icon: FaVideo },
  { label: "Globe", value: "FaGlobe", icon: FaGlobe },
  { label: "Cloud", value: "FaCloud", icon: FaCloud },
  { label: "Mobile", value: "FaMobileAlt", icon: FaMobileAlt },
  { label: "Networking", value: "FaNetworkWired", icon: FaNetworkWired },
  { label: "Server", value: "FaServer", icon: FaServer },
  { label: "AI Robot", value: "FaRobot", icon: FaRobot },
  { label: "Brain", value: "FaBrain", icon: FaBrain },
  { label: "Language", value: "FaLanguage", icon: FaLanguage },
  { label: "Education", value: "FaGraduationCap", icon: FaGraduationCap },
  { label: "Science", value: "FaFlask", icon: FaFlask },
  { label: "Nature", value: "FaLeaf", icon: FaLeaf },
  { label: "Ecommerce", value: "FaShoppingCart", icon: FaShoppingCart },
  { label: "Finance", value: "FaChartLine", icon: FaChartLine },
  { label: "Money", value: "FaMoneyBillWave", icon: FaMoneyBillWave },
  { label: "Idea", value: "FaRegLightbulb", icon: FaRegLightbulb },
  { label: "Engineering", value: "FaCogs", icon: FaCogs },
  { label: "Energy", value: "FaBolt", icon: FaBolt },
  { label: "Security", value: "FaLock", icon: FaLock },
  { label: "Keyboard", value: "FaKeyboard", icon: FaKeyboard },
  { label: "Puzzle", value: "FaPuzzlePiece", icon: FaPuzzlePiece },
  { label: "Tools", value: "FaWrench", icon: FaWrench },
  { label: "Navigation", value: "FaCompass", icon: FaCompass },
  { label: "Sports", value: "FaRunning", icon: FaRunning },
  { label: "Fitness", value: "FaDumbbell", icon: FaDumbbell },
  { label: "Health", value: "FaHeartbeat", icon: FaHeartbeat },
  { label: "Hospital", value: "FaHospital", icon: FaHospital },
  { label: "Medicine", value: "FaPills", icon: FaPills },
  { label: "First Aid", value: "FaMedkit", icon: FaMedkit },
  { label: "Doctor", value: "FaStethoscope", icon: FaStethoscope },
  { label: "Food", value: "FaAppleAlt", icon: FaAppleAlt },
  { label: "Car", value: "FaCar", icon: FaCar },
  { label: "Bus", value: "FaBus", icon: FaBus },
  { label: "Plane", value: "FaPlane", icon: FaPlane },
  { label: "Ship", value: "FaShip", icon: FaShip },
  { label: "Bicycle", value: "FaBicycle", icon: FaBicycle },
  { label: "Tractor", value: "FaTractor", icon: FaTractor },
  { label: "Gaming", value: "FaGamepad", icon: FaGamepad },
  { label: "Rocket", value: "FaRocket", icon: FaRocket },
  { label: "Atom", value: "FaAtom", icon: FaAtom },
  { label: "Microscope", value: "FaMicroscope", icon: FaMicroscope },
  { label: "Reading", value: "FaBookOpen", icon: FaBookOpen },
  { label: "Writing", value: "FaPenFancy", icon: FaPenFancy },
  { label: "Drama", value: "FaTheaterMasks", icon: FaTheaterMasks },
  { label: "Film", value: "FaFilm", icon: FaFilm },
  { label: "Podcast", value: "FaPodcast", icon: FaPodcast },
  { label: "Notifications", value: "FaBell", icon: FaBell },
  { label: "Email", value: "FaEnvelope", icon: FaEnvelope },
  { label: "Phone", value: "FaPhone", icon: FaPhone },
  { label: "Clock", value: "FaClock", icon: FaClock },
  { label: "Calendar", value: "FaCalendarAlt", icon: FaCalendarAlt },
  { label: "Maps", value: "FaMapMarkedAlt", icon: FaMapMarkedAlt },
  { label: "Building", value: "FaBuilding", icon: FaBuilding },
  { label: "University", value: "FaUniversity", icon: FaUniversity },
  { label: "Industry", value: "FaIndustry", icon: FaIndustry },
  { label: "Repair", value: "FaTools", icon: FaTools },
  { label: "Hammer", value: "FaHammer", icon: FaHammer },
  { label: "Brush", value: "FaBrush", icon: FaBrush },
  { label: "Pencil", value: "FaPencilAlt", icon: FaPencilAlt },
  { label: "Lightbulb", value: "FaLightbulb", icon: FaLightbulb },
  { label: "Sun", value: "FaSun", icon: FaSun },
  { label: "Moon", value: "FaMoon", icon: FaMoon },
  { label: "Star", value: "FaStar", icon: FaStar },
  { label: "Heart", value: "FaHeart", icon: FaHeart },
  { label: "Smile", value: "FaSmile", icon: FaSmile },
  { label: "Sad", value: "FaFrown", icon: FaFrown },
  { label: "Dog", value: "FaDog", icon: FaDog },
  { label: "Cat", value: "FaCat", icon: FaCat },
  { label: "Fish", value: "FaFish", icon: FaFish },
  { label: "Horse", value: "FaHorse", icon: FaHorse },
  { label: "Tree", value: "FaTree", icon: FaTree },
  { label: "Mountain", value: "FaMountain", icon: FaMountain },
  { label: "Water", value: "FaWater", icon: FaWater },
  { label: "Fire", value: "FaFire", icon: FaFire },
  { label: "Recycle", value: "FaRecycle", icon: FaRecycle },
  { label: "Gift", value: "FaGift", icon: FaGift },
  { label: "Shopping Bag", value: "FaShoppingBag", icon: FaShoppingBag },
  { label: "Credit Card", value: "FaCreditCard", icon: FaCreditCard },
  { label: "Wallet", value: "FaWallet", icon: FaWallet },
  { label: "Coding", value: "FaLaptopCode", icon: FaLaptopCode },
  { label: "Chip", value: "FaMicrochip", icon: FaMicrochip },
  { label: "Satellite", value: "FaSatellite", icon: FaSatellite },
  { label: "Space Shuttle", value: "FaSpaceShuttle", icon: FaSpaceShuttle },
  { label: "Trophy", value: "FaTrophy", icon: FaTrophy },
  { label: "Medal", value: "FaMedal", icon: FaMedal },
  { label: "Flag", value: "FaFlag", icon: FaFlag },
  { label: "Glasses", value: "FaGlasses", icon: FaGlasses },
  { label: "Pen", value: "FaPenNib", icon: FaPenNib },
  { label: "Box", value: "FaBox", icon: FaBox },
  { label: "Archive", value: "FaArchive", icon: FaArchive },

  // 🖥️ Programming Languages
  { label: "JavaScript", value: "DiJavascript1", icon: DiJavascript1 },
  { label: "TypeScript", value: "SiTypescript", icon: SiTypescript },
  { label: "Python", value: "FaPython", icon: FaPython },
  { label: "Java", value: "FaJava", icon: FaJava },
  { label: "PHP", value: "FaPhp", icon: FaPhp },

  // 🎨 Frontend
  { label: "React", value: "FaReact", icon: FaReact },
  { label: "Next.js", value: "SiNextdotjs", icon: SiNextdotjs },
  { label: "Angular", value: "FaAngular", icon: FaAngular },
  { label: "Vue.js", value: "FaVuejs", icon: FaVuejs },
  { label: "HTML5", value: "FaHtml5", icon: FaHtml5 },
  { label: "CSS3", value: "FaCss3", icon: FaCss3 },
  { label: "TailwindCSS", value: "SiTailwindcss", icon: SiTailwindcss },

  // ⚙️ Backend
  { label: "Node.js", value: "FaNodeJs", icon: FaNodeJs },
  { label: "Django", value: "SiDjango", icon: SiDjango },
  { label: "Spring Boot", value: "SiSpring", icon: SiSpring },

  // 🗄️ Databases
  { label: "MongoDB", value: "SiMongodb", icon: SiMongodb },
  { label: "MySQL", value: "SiMysql", icon: SiMysql },
  { label: "PostgreSQL", value: "SiPostgresql", icon: SiPostgresql },

  // ☁️ DevOps & Cloud
  { label: "Docker", value: "FaDocker", icon: FaDocker },
  { label: "Kubernetes", value: "SiKubernetes", icon: SiKubernetes },
  { label: "AWS", value: "FaAws", icon: FaAws },
  { label: "Git", value: "FaGitAlt", icon: FaGitAlt },

  // 🛠️ APIs
  { label: "GraphQL", value: "SiGraphql", icon: SiGraphql },
];


export const getCourseIcon = (iconName) => {
  const iconObj = courseIcons.find((c) => c.value === iconName);
  return iconObj ? iconObj.icon : null;
};